### ISSUE TITLE
Parallel Playwright execution in Kubernetes

### ISSUE THREAD

**Issue by vania-pooh** [playwright-community/playwright-community#14]
We added this to aerokube.com/moon/latest/#_using_playwright

**Comment by mxschmitt** [comment]
@vania-pooh do you want to write a blog article about it?
Feel free to add it here too: https://github.com/mxschmitt/awesome-playwright

**Comment by mxschmitt** [comment]
@vania-pooh  Please share with us the intention why you've opened this issue, thanks!

**Comment by vania-pooh** [comment]
@mxschmitt I thought this is an expected way of proposing Playwright-related news to be published in https://playwright.tech.
