### ISSUE TITLE
Vercel/AWS lambda 50MB limit

### ISSUE THREAD

**Issue by italodeandra** [playwright-community/playwright-community#46]
Hi, really nice showcase.

I'm using this as a reference for my project, but sadly I can't create a Serverless Function with Playwright (like `thumbnail.ts`) because the Chromium binary is too big for it. Do you guys have any tip on how you fit it on this project?

**Comment by mxschmitt** [comment]
Are you using the following package? https://github.com/alixaxel/chrome-aws-lambda/#usage-with-playwright
(it's important to not use playwright or playwright-chromium there. Only playwright-core is needed.)

**Comment by italodeandra** [comment]
Yes, but sadly the latest version is already 48MB compressed. I can't get lower than 52MB, and I removed everything that I didn't need (even though it was pointless because webpack already do a really good job removing it).

**Comment by italodeandra** [comment]
One workaround I found is to use an older version with is smaller. But I was unable to make it work on Vercel.

Either way, I'll close this issue cause I decided to host my Next.js application elsewhere (so no lambda limits).
